import { Inter,Calistoga,Nunito } from "next/font/google";
import "./globals.css";

const calistoga = Nunito({
  // Correct weight without 'px'
  subsets: ['latin'],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={calistoga.className}>{children}</body>
    </html>
  );
}
